apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            limits:
              memory: 2Gi
              cpu: 1
          env:
            - name: discovery.type
              value: single-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmp-app
  template:
    metadata:
      labels:
        app: openmp-app
    spec:
      containers:
        - name: openmp-container
          image: docker.io/marcelog5/openmp-service:1.0.0.6
          ports:
            - containerPort: 1234
          resources:
            limits:
              memory: 2Gi
              cpu: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.14.0
          ports:
            - containerPort: 5601
          resources:
            limits:
              memory: 1Gi
              cpu: 0.5
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200" # Endereço do Elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-server
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
        - name: tcp-server
          image: docker.io/washingtonbispo/tcp-server:latest
          ports:
            - containerPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
        - name: spark-app
          image: docker.io/washingtonbispo/pspd-spark:latest
          ports:
            - containerPort: 7071  # Substitua pela porta do Spark Web UI, se necessário
          env:
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7077"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: openmp-service
spec:
  selector:
    app: openmp-app
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server-service
spec:
  selector:
    app: tcp-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spark-app-service
spec:
  selector:
    app: spark-app
  ports:
    - protocol: TCP
      port: 7071
      targetPort: 7071
  type: LoadBalancer