apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-server
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
        - name: tcp-server
          image: docker.io/thiagogmf/tcp-server:1.0.1
          ports:
            - containerPort: 8888
